CREATE DATABASE pharmadb;
USE pharmadb;

CREATE TABLE usuarios(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nombre VARCHAR(45) NOT NULL,
apellidos VARCHAR(45) NOT NULL,
telefono VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
permiso INT(11) NOT NULL,
contrasena VARCHAR(45) NOT NULL
);

INSERT INTO USUARIOS(ID,NOMBRE,APELLIDOS,TELEFONO,EMAIL,PERMISO)
VALUES ('1','Amanda','Aguirre Arias','601001001','amanda@aguirre.com','1');
INSERT INTO USUARIOS(ID,NOMBRE,APELLIDOS,TELEFONO,EMAIL,PERMISO)
VALUES ('2','Borja','Barriga Barragan','602002002','borja@barriga.com','1');
INSERT INTO USUARIOS(ID,NOMBRE,APELLIDOS,TELEFONO,EMAIL,PERMISO)
VALUES ('3','Carlos','Colmenares Carreño','603003003','carlos@colmenares.com','9');

CREATE TABLE direcciones(
id_direccion INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id INT NOT NULL,
calle VARCHAR(45) NOT NULL,
ciudad VARCHAR(45) NOT NULL,
provincia VARCHAR(45) NOT NULL,
cod_postal INT NOT NULL,
FOREIGN KEY (id) REFERENCES usuarios(id)
);

INSERT INTO DIRECCIONES(ID_DIRECCION,ID,CALLE,CIUDAD,PROVINCIA,COD_POSTAL) VALUES ('1','1','Abalos 1, 1-1','Madrid','Madrid','28001');
INSERT INTO DIRECCIONES(ID_DIRECCION,ID,CALLE,CIUDAD,PROVINCIA,COD_POSTAL) VALUES ('2','2','Butarque 2, 2-2','Madrid','Madrid','28002');
INSERT INTO DIRECCIONES(ID_DIRECCION,ID,CALLE,CIUDAD,PROVINCIA,COD_POSTAL) VALUES ('3','3','Carmino 3, 3-3','Madrid','Madrid','28003');

CREATE TABLE productos(
cod_producto INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
tipo INT(11) NOT NULL,
nombre VARCHAR(45) NOT NULL,
presentacion VARCHAR(45),
detalles TINYTEXT,
proveedor VARCHAR(45) NOT NULL,
precio_uni FLOAT NOT NULL,
foto VARCHAR(45)
);

INSERT INTO PRODUCTOS(COD_PRODUCTO,TIPO,NOMBRE,PRESENTACION,DETALLES,PROVEEDOR,PRECIO_UNI) 
VALUES ('1','1','Amoxicilina 500mg','30 comprimidos','','La Sante','1.10');
INSERT INTO PRODUCTOS(COD_PRODUCTO,TIPO,NOMBRE,PRESENTACION,DETALLES,PROVEEDOR,PRECIO_UNI) 
VALUES ('2','2','Tensiometro','','Digital de Brazo','Omron','20.50');
INSERT INTO PRODUCTOS(COD_PRODUCTO,TIPO,NOMBRE,PRESENTACION,DETALLES,PROVEEDOR,PRECIO_UNI) 
VALUES ('3','3','Esparadrapo','6 unds','','3M','5.70');

CREATE TABLE inventario(
id_inv INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
cod_producto INT NOT NULL,
cantidad INT NOT NULL,
FOREIGN KEY (cod_producto) REFERENCES productos(cod_producto)
);

INSERT INTO INVENTARIO(ID_INV,COD_PRODUCTO,CANTIDAD) VALUES ('1','1','25');
INSERT INTO INVENTARIO(ID_INV,COD_PRODUCTO,CANTIDAD) VALUES ('2','2','5');
INSERT INTO INVENTARIO(ID_INV,COD_PRODUCTO,CANTIDAD) VALUES ('3','3','18');

CREATE TABLE orden(
id_orden INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id INT NOT NULL,
id_direccion INT NOT NULL,
estado VARCHAR(45) NOT NULL,
calcular_total FLOAT NOT NULL,
FOREIGN KEY (id) REFERENCES usuarios(id),
FOREIGN KEY (id_direccion) REFERENCES direcciones(id_direccion)
);

CREATE TABLE orden_detalle(
id_detalle INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id_orden INT NOT NULL,
cod_producto INT NOT NULL,
cantidad INT NOT NULL,
precio_uni FLOAT NOT NULL,
FOREIGN KEY (id_orden) REFERENCES orden(id_orden),
FOREIGN KEY (cod_producto) REFERENCES productos(cod_producto)
);




